logging:
  level: INFO
  loggers:
    com.dropwizard: DEBUG

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: rahul
    # the password
    password: rahul2310
    # the JDBC URL; the database is called hello_world
    url: jdbc:mysql://localhost:3306/employee_attendance
